name: Test Publish
on:
  push:
    branches:
      - chore/setup-repository
jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Mock the release tarball URL since we don't have an actual release
      - run: git archive --format=tar.gz -o source.tar.gz HEAD
      - uses: CheckerNetwork/web3-storage-upload-file-action@v0
        id: upload
        with:
          path: source.tar.gz
          private-key: ${{ secrets.W3UP_PRIVATE_KEY }}
          proof: ${{ secrets.W3UP_PROOF }}
      - uses: CheckerNetwork/w3name-update-action@v0
        with:
          value: "/ipfs/${{ steps.upload.outputs.cid }}"
          private-key: ${{ secrets.W3NAME_PRIVATE_KEY }}
          revision: ${{ secrets.W3NAME_REVISION }}
